spring.profiles.active: development
---
spring:
  profiles: development
  data:
    neo4j:
      uri: bolt://192.168.99.100:7687
      username: neo4j
      password: secret
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.99.100:8761/eureka/
---
spring:
  profiles: docker
  data:
    neo4j:
      uri: bolt://neo4j:7687
      username: neo4j
      password: secret
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: test
  data:
    neo4j:
      uri: bolt://192.168.99.101:7687
      username: neo4j
      password: secret
eureka:
  client:
    enabled: false