spring:
  profiles:
    active: development
---
spring:
  profiles: development
  application:
    name: online-store-web
zuul:
  ignored-services: '*'
  routes:
    edge-service:
      path: /api/**
      url: http://192.168.99.100:9999
    auth-service:
      path: /user/**
      url: http://192.168.99.100:8181/uaa/user
security:
#  enable-csrf: false
  oauth2:
    resource:
      user-info-uri: http://192.168.99.100:8181/uaa/user
    client:
      access-token-uri: http://192.168.99.100:8181/uaa/oauth/token
      user-authorization-uri: http://192.168.99.100:8181/uaa/oauth/authorize
      client-id: acme
      client-secret: acmesecret
#  ignored: /assets/**
eureka:
  instance:
    non-secure-port: 8787
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.99.100:8761/eureka/
---
spring:
  profiles: docker
  application:
    name: online-store-web
zuul:
  ignored-services: '*'
  routes:
    edge-service:
      path: /api/**
      url: http://${DOCKER_IP:192.168.99.100}:9999
    auth-service:
      path: /user/**
      url: http://${DOCKER_IP:192.168.99.100}:8181/uaa/user
security:
#  enable-csrf: false
  oauth2:
    resource:
      user-info-uri: http://${DOCKER_IP:192.168.99.100}:8181/uaa/user
    client:
      access-token-uri: http://${DOCKER_IP:192.168.99.100}:8181/uaa/oauth/token
      user-authorization-uri: http://${DOCKER_IP:192.168.99.100}:8181/uaa/oauth/authorize
      client-id: acme
      client-secret: acmesecret
eureka:
  instance:
    non-secure-port: 8787
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/